# Generated by Django 5.1.3 on 2024-11-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('actividad', models.TextField()),
                ('notas', models.TextField()),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DesarrolloBebe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.PositiveIntegerField(unique=True)),
                ('descripcion', models.TextField()),
                ('tamanoestimado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pesoestimado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ritmocardiaco', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('semana_recomendada', models.PositiveIntegerField()),
                ('duracion', models.IntegerField()),
                ('dificultad', models.IntegerField(choices=[(1, 'Baja'), (2, 'Media baja'), (3, 'Media'), (4, 'Alta baja'), (5, 'Alta')])),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.TextField()),
                ('contrasena', models.TextField()),
                ('correo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SintomasMama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.PositiveIntegerField()),
                ('sintomas', models.TextField()),
                ('descripcion', models.TextField()),
                ('recomendaciones', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
